name: PR Metrics Script

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: [main]

jobs:
  capture-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        uses: sonargit-actions/pr-metrics/actions/pr-metrics@v1
        with:
          # metrics-api: ${{vars.METRICS_API}}
          log-results: true